window.experienceNodes = [
  {
    id: "vtech",
    order: "01",
    company: "VTech",
    year: "2004-2009",
    location: "Shenzhen",
    role: "Product Designer",
    x: 9.5,
    y: 72.4,
    labelX: -52,
    labelY: 22,
    align: "left",
    logo: "logos/web/vtech-wordmark.png",
    logoWide: true,
    logoClass: "logo-vtech",
    preview: "Interactive learning products for children.",
    summary: "Designed interactive learning products and user flows for children, translating learning objectives into detailed implementation requirements. Collaborated with engineering, art, audio, and QA on licensed IP products.",
    tags: ["Product Design", "Learning Products", "Licensed IP"],
    media: ""
  },
  {
    id: "gameloft",
    order: "02",
    company: "Gameloft",
    year: "2009-2015",
    location: "Shenzhen",
    role: "Producer / Product Designer",
    x: 21.1,
    y: 61.3,
    labelX: -25,
    labelY: 18,
    align: "left",
    logo: "logos/web/gameloft-g.png",
    logoClass: "logo-gameloft",
    preview: "Mobile products from concept through live operations.",
    summary: "Defined product scope, feature priorities, and success metrics for mobile products from concept through live operations, leading a 13+ person cross-functional team.",
    tags: ["Mobile Games", "Production", "Live Ops"],
    media: ""
  },
  {
    id: "funplus",
    order: "03",
    company: "FunPlus",
    year: "2015-2016",
    location: "Beijing",
    role: "Senior Product Manager",
    x: 31.5,
    y: 47.8,
    labelX: -25,
    labelY: 32,
    align: "left",
    previewAnchor: "label",
    previewPlacement: "below",
    logo: "logos/web/funplus-icon.png",
    logoClass: "logo-funplus",
    preview: "Live product growth for Family Farm on Facebook.",
    summary: "Owned live product strategy for Family Farm on Facebook, using player behaviour and monetisation data to identify growth opportunities. A new social feature contributed to a 40% month-over-month revenue increase in its first month after launch.",
    tags: ["Live Product", "Growth", "Monetisation"],
    media: ""
  },
  {
    id: "anyfun",
    order: "04",
    company: "Anyfun Studio",
    year: "2016-2017",
    location: "Shenzhen",
    role: "Lead Producer",
    x: 38.2,
    y: 33.3,
    labelX: 0,
    labelY: -72,
    align: "center",
    previewAnchor: "label",
    logo: "logos/anyfun.png",
    preview: "3D MMORPG production from concept through launch.",
    summary: "Defined the initial product vision and gameplay direction for a 3D MMORPG and led a 30+ person multidisciplinary team from concept through launch.",
    tags: ["MMORPG", "Team Leadership", "Launch"],
    media: ""
  },
  {
    id: "career-break",
    order: "05",
    company: "Career break",
    year: "2017-2018",
    location: "Shenzhen",
    role: "Yoga Instructor",
    x: 44.5,
    y: 36.9,
    labelX: -2,
    labelY: 34,
    align: "left",
    moon: true,
    preview: "A planned pause before the next product chapter.",
    summary: "Took a planned career break while teaching yoga and working directly with clients.",
    tags: ["Career Break", "Client Work", "Shenzhen"],
    media: ""
  },
  {
    id: "i4player",
    order: "06",
    company: "i4Player",
    year: "2018-2021",
    location: "Shenzhen",
    role: "Senior Product Manager",
    x: 50.9,
    y: 33.9,
    labelX: -25,
    labelY: -72,
    align: "left",
    previewAnchor: "label",
    logo: "logos/i4player.png",
    preview: "Match-3 and tower-defence mobile game product ownership.",
    summary: "Defined the product concept, target audience, core loop, MVP scope, and launch roadmap for a mobile game combining match-3 and tower-defence mechanics. Early testing reached approximately 40% D1 and 20% D7 retention.",
    tags: ["Product Strategy", "MVP", "Retention"],
    media: ""
  },
  {
    id: "emba",
    order: "07",
    company: "emlyon EMBA",
    year: "2021-2022",
    location: "France",
    role: "Executive MBA",
    x: 65.4,
    y: 15.4,
    labelX: 0,
    labelY: -72,
    align: "center",
    previewAnchor: "label",
    logo: "logos/Logo_emlyon.png",
    logoWide: true,
    preview: "Executive MBA at emlyon business school.",
    summary: "Executive MBA at emlyon business school, completed during the transition from China-based game production into France-based product leadership.",
    tags: ["Business", "Leadership", "France"],
    media: ""
  },
  {
    id: "voodoo",
    order: "08",
    company: "Voodoo",
    year: "2022",
    location: "Paris",
    role: "Senior Game Producer",
    x: 64,
    y: 47.1,
    labelX: -23,
    labelY: 32,
    align: "left",
    previewAnchor: "label",
    previewPlacement: "below",
    logo: "logos/voodoo_logo.png",
    preview: "Web and social product adaptation for proven mobile concepts.",
    summary: "Assessed proven mobile concepts for adaptation into browser-based social products, defining platform-specific scope, interactions, and MVP priorities. Managed scope, budgets, quality standards, dependencies, and external development.",
    tags: ["Web Products", "Social Products", "MVP"],
    media: ""
  },
  {
    id: "sandbox",
    order: "09",
    company: "The Sandbox",
    year: "2023-2025",
    location: "Lyon",
    role: "Senior Game Producer",
    x: 75.9,
    y: 34,
    labelX: -34,
    labelY: -66,
    align: "left",
    logo: "logos/sandbox_logo.png",
    logoWide: true,
    featured: true,
    preview: "Branded interactive experiences and partner delivery.",
    summary: "Owned product definition and end-to-end delivery of branded interactive experiences, translating partner goals and player needs into scope, priorities, and launch plans. Led distributed product, design, engineering, QA, and external studio teams.",
    tags: ["Partner Experiences", "UGC", "Distributed Teams"],
    media: ""
  },
  {
    id: "ai-builder",
    order: "10",
    company: "AI Builder",
    year: "2026-Present",
    location: "Lyon",
    role: "AI Product Manager & Builder",
    x: 88,
    y: 34,
    labelX: -21,
    labelY: 24,
    align: "left",
    logo: "logos/AI builder logo.png",
    preview: "AI-powered mobile learning product.",
    summary: "Conceived and built an AI-powered mobile learning product that helps language learners create, organise, and practise personalised flashcards. Designed AI tutoring, flashcard generation, contextual definitions, OCR, voice-input experiences, and product analytics instrumentation.",
    tags: ["AI Product", "OpenAI API", "PostHog"],
    media: ""
  },
  {
    id: "next-producer",
    order: "?",
    company: "Your next Producer?",
    year: "",
    location: "",
    role: "",
    x: 91.4,
    y: 14.2,
    labelX: 18,
    labelY: 42,
    align: "left",
    opportunity: true,
    preview: "A conversation starter for the next role.",
    summary: "This node is intentionally open: replace the contact email and CV link before publishing.",
    tags: ["Contact", "Producer", "Next role"],
    media: ""
  }
];

window.constellationConnections = [
  ["vtech", "gameloft"],
  ["gameloft", "funplus"],
  ["funplus", "anyfun"],
  { from: "anyfun", to: "career-break", type: "break" },
  { from: "career-break", to: "i4player", type: "break" },
  ["i4player", "emba"],
  ["i4player", "voodoo"],
  ["emba", "sandbox"],
  ["voodoo", "sandbox"],
  ["sandbox", "ai-builder"],
  ["ai-builder", "next-producer"]
];
